from moviepy.editor import VideoFileClip, TextClip, CompositeVideoClip

def add_text_overlay(video_path, text, output_path):
    """
    Adds a text overlay to a video.

    Args:
        video_path (str): The path to the input video file.
        text (str): The text to overlay on the video.
        output_path (str): The path to save the output video file.
    """
    # Load the video clip
    video_clip = VideoFileClip(video_path)

    # Create a text clip. You can customize the font, size, color, etc.
    text_clip = TextClip(text, fontsize=70, color='white')

    # Set the position of the text clip and its duration
    text_clip = text_clip.set_pos('center').set_duration(video_clip.duration)

    # Overlay the text clip on the video clip
    final_clip = CompositeVideoClip([video_clip, text_clip])

    # Write the result to a file
    final_clip.write_videofile(output_path, codec='libx264')

# Example usage:
#
# from src.video_editor.editor import add_text_overlay
#
# # This assumes you have a video file named 'input.mp4' in the same
# # directory as your script.
# add_text_overlay('input.mp4', 'Hello, World!', 'output.mp4')
#
# In our main application, we'll be calling this function with the
# video generated by Runway.
